<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>First Page</title>
    <meta charset="UTF-8" />
</head>

<body>
    <p>This page mixes static HTML with HTML dynamically generated by PHP.</p>
    <p>The page is served by <?php echo __FILE__ ?>.</p>
    <p>Today is <?php echo date("Y-m-d") ?>. It is <?php echo date("H:i:s") ?>.</p>
    <?php include "included-file.php" ?>
    <p>The page uses PHP <?php echo PHP_VERSION ?>.</p>
</body>

</html>